## NOTE THIS CLASS IS AUTOGENERATED BY THE APIDOC GENERATOR
## TO CHANGE: script/apidoc/template/apidoc_controller.rb.erb and regenerate
require 'rest_client'
require 'json'

class ApiController < ApplicationController
end
